version: 0.1

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 381492132216.dkr.ecr.ap-south-1.amazonaws.com/flask-app-cicd
      - echo "Logged in to Amazon ECR successfully."

  build:
    commands:
      - echo "Building Docker Image for Flask Application"
      - docker build -t flask_image .
      - echo "Image built successfully."

  post_build:
    commands:
      - echo "Tagging Flask Docker image"
      - docker tag flask_image:latest 381492132216.dkr.ecr.ap-south-1.amazonaws.com/flask-app-cicd/image1
      - docker push 381492132216.dkr.ecr.ap-south-1.amazonaws.com/flask-app-cicd/image1
      - echo "Flask image pushed to ECR"
